# Generated by Django 3.2 on 2021-04-23 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='closet',
            name='description',
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='closet_app.closet')),
            ],
        ),
    ]
