# Generated by Django 3.2 on 2021-04-25 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closet_app', '0002_auto_20210423_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='closet', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='closet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet', to='closet_app.closet'),
        ),
    ]
