# Generated by Django 3.2 on 2021-04-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet_app', '0003_auto_20210425_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='closet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='closet_app.closet'),
        ),
    ]
